spring:
  thymeleaf:
    mode: LEGACYHTML5
  resources:
    chain:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: blog
    password: blog
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
